#ifndef DATA_PROCESSOR_H
#define DATA_PROCESSOR_H

#include <string>
#include <vector>
#include <map>
#include <utility>

// ============================================================================
// TYPE ALIASES
// ============================================================================

// Type alias for pair of long long values (used for returning new/used car counts)
typedef std::pair<long long, long long> pll;

// ============================================================================
// DATA STRUCTURES
// ============================================================================

// Represents a single row from the CSV file
struct SaleRecord
{
	std::string sale_date;      // Date of sale (format: YYYY-MM-DD)
	std::string country;        // Country where sale occurred
	std::string manufacturer;   // Car manufacturer/brand (e.g., Audi, BMW)
	std::string condition;      // Condition of car (New or Used)
	std::string region;         // Geographic region (e.g., Europe, Asia)
	double sale_price_usd;      // Sale price in USD
};

// Stores the column indices from the CSV header
// Used to map column positions to data fields when parsing each row
struct ColumnIndices
{
	int sale_date;
	int country;
	int manufacturer;
	int condition;
	int sale_price_usd;
	int region;
};

// ============================================================================
// CSV PARSING FUNCTIONS
// ============================================================================

// Extract next comma-separated token from a string_view
// Modifies the string_view to point past the extracted token
// Returns the extracted token as a string_view
inline std::string_view next_token(std::string_view& sv);

// Parse the CSV header line and build a map of column names to indices
// Returns a ColumnIndices struct with the position of each required column
ColumnIndices buildColumnIndices(const std::string& headerLine);

// Parse a single CSV line into a SaleRecord using the column indices
// Only extracts columns up to the maximum required index for efficiency
SaleRecord parseLine(const std::string& line, const ColumnIndices& indices);

// ============================================================================
// DATA EXTRACTION FUNCTIONS
// ============================================================================

// Extract year from date string (assumes YYYY-MM-DD format)
// Returns -1 if parsing fails
int extractYear(const std::string& dateStr);

// Count new and used Audi cars sold in a specific year and country
// Returns a pair: {newCarCount, usedCarCount}
pll countAudiCarsSoldInYear(const std::string& filename, int targetYear, 
                            const std::string& brand, const std::string& country);

// Calculate total revenue generated by a specific manufacturer across all regions and years
long long totalRevenueGeneratedByBMW(const std::string& filename, const std::string& brand);

// Build a map of country -> total revenue for a specific manufacturer in a specific region
void revenueDistributionOfBMWInEurope(const std::string& filename, const std::string& brand, 
                                       std::map<std::string, long long>& regionRevenue);

// ============================================================================
// DISPLAY FUNCTIONS
// ============================================================================

// Display first N records from the CSV file (for verification/testing)
void displaySampleRecords(const std::string& filename, int maxRecords = 5);

// ============================================================================
// MULTI-QUERY FUNCTION - SINGLE PASS OPTIMIZATION
// ============================================================================

// Compute multiple aggregates in a single pass through the file
// This is more efficient than calling separate functions that each read the file
// Calculates:
//   1. Audi cars sold in China in 2025 (new vs used)
//   2. Total BMW revenue in 2025
//   3. BMW revenue distribution across European countries
void ComputeEverythingInSinglePass(const std::string& filename, 
                                   std::map<std::string, long long>& regionRevenue);

#endif // DATA_PROCESSOR_H
