#define _CRT_SECURE_NO_WARNINGS
#define NOMINMAX

#include <iostream>
#include <map>
#include "DataProcessor.h"

// ============================================================================
// MAIN FUNCTION
// ============================================================================

int main()
{
	// Filename of the CSV data source
	const std::string filename = "world_car_sales_1m.csv";
	
	// Map to store BMW revenue distribution across European countries
	std::map<std::string, long long> regionRevenue;

	// Display sample records for verification (uncomment to enable)
	// displaySampleRecords(filename, 5);

	// ========================================================================
	// OPTION 1: Run individual queries (less efficient - multiple file passes)
	// ========================================================================
	

	// Query 1: Count Audi cars in China in 2025
	/*pll audiCount = countAudiCarsSoldInYear(filename, 2025, "Audi", "China");

	if (audiCount.first + audiCount.second >= 0) {
		std::cout << "\n--- Audi Cars in China (2025) ---\n";
		std::cout << "Number of New Audi cars: " << audiCount.first << std::endl;
		std::cout << "Number of Used Audi cars: " << audiCount.second << std::endl;
		std::cout << "Total: " << (audiCount.first + audiCount.second) << std::endl;
	}

	// Query 2: Total BMW revenue
	long long BMWTotalRevenue = totalRevenueGeneratedByBMW(filename, "BMW");
	if (BMWTotalRevenue >= 0) {
		std::cout << "\nTotal revenue generated by BMW: $" << BMWTotalRevenue << std::endl;
	}

	// Query 3: BMW revenue distribution in Europe
	regionRevenue.clear();
	revenueDistributionOfBMWInEurope(filename, "BMW", regionRevenue);
	std::vector<std::pair<std::string, long long>> sortedRevenue(regionRevenue.begin(), regionRevenue.end());
	
	std::sort(sortedRevenue.begin(), sortedRevenue.end(),
		[](const std::pair<std::string, long long>& lhs, const std::pair<std::string, long long>& rhs)
		{
			return lhs.second > rhs.second;
		}
	);

	std::cout << "\nBMW Revenue distribution in Europe (highest to lowest):\n";
	for (const auto& pr : sortedRevenue)
	{
		std::cout << pr.first << ": $" << pr.second << std::endl;
	}
	*/

	// ========================================================================
	// OPTION 2: Run optimized single-pass analysis (RECOMMENDED)
	// ========================================================================
	// This approach reads the file only once and computes all metrics together
	// Much more efficient for large datasets!
	
	regionRevenue.clear();
	ComputeEverythingInSinglePass(filename, regionRevenue);
	getchar(); // Pause before exit
	return 0;
}